package.json
"istanbul" is a peer dependency of "grunt-mocha-istanbul".
Starting with npm v3.0.0 it won't be be automatically installed
anymore and an explicit dependency is required.
Warning from npm v2.x
```shell
npm WARN peerDependencies The peer dependency istanbul@0.x.x included from grunt-mocha-istanbul will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```
=> add missing "istanbul" devDependency

src/client/assets/styles/_landing-page.scss
upper right "Sign In" link has a dark hover color which is hard
to read as the background image is quite dark as well.
changed the color to be the same as without hover (white).
Before
After
=> fix sign-in link hover color

DESCRIPTION.MD, README.md, src/client/login.html, src/client/templates/home.html
Removing errant apostrophes from plural uses of CLA. (CLA's -> CLAs) to match with style guide: http://www.oxforddictionaries.com/words/apostrophe
=> Remove apostrophe from plural for CLAs

src/server/services/pullRequest.js, src/tests/server/services/pullRequest.js
#110 only dealt with the case of a single committer, this uses the same language for >1 committer, too.
=> Friendlier PR comment for >1 committer

src/client/controller/home.js, src/client/templates/home.html, src/client/templates/settings.html, src/server/api/cla.js, src/server/documents/org.js, src/server/services/org.js, src/server/webhooks/pull_request.js, src/tests/server/api/cla.js, src/tests/server/documents/org.js, src/tests/server/testData.js, src/tests/server/webhooks/pull_request.js
This change adds a field "excludePattern" to the org model, which allows to specify a comma-separated list of repository names or substrings which are matched against the repository of an incoming or rechecked PR. If the string matches against the repo name, the PR is ignored and no
CLA check is done.
Fixes #157.
=> Allowing to specify patterns for ignored repos during org linking

README.md
[MongoLab is now mLab](http://blog.mlab.com/2016/02/mongolab-is-now-mlab/), it seems worthwhile to update the README.md's link in case they decide to drop the old domain.
=> Reflect mongolab name change in README.md.

src/client/assets/styles/_navbar.scss, src/client/assets/styles/app.scss, src/client/home.html, src/client/templates/cla.html
Fixes for https://github.com/cla-assistant/cla-assistant/issues/155 and https://github.com/cla-assistant/cla-assistant/issues/149
1. Use parameters for header and footer sizes.
2. Update cla and home pages to use consistent content whitespace.
**CLA page**
Note: Consistent with other CLA forms (e.g. [Github](https://cla.github.com/agreement), [Google](https://cla.developers.google.com/about/google-individual?csw=1), [jquery](https://js.foundation/CLA/)) the complete CLA is displayed. The width uses standard bootstrap responsive widths, a couple of different widths shown below.
Before
After
Before (wide)
After (wide)
**Home page**
Note: This fix also makes the initial vertical whitespace on the home page consistent with the cla page.
Before
After
=> Style changes for CLA signer page.

src/server/controller/badge.js
Following up on #219. Unfortunately I couldn't test this locally.
Now it always appends a '?'. Then followed by the individual key value pairs separated by '&'.
=> Use & concatenation.

src/server/controller/counts.js
DocumentDB now supports almost all the MongoDB APIs. However, they are still working on aggregation with group by. So it will return an error with '$group' is not supported'. This is a simple fix to avoid crash when using documentDB. Feel free to give me some feedback. Thank you :)
=> Avoid crash when using documentDB to replace mongoDB on Azure.

src/client/controller/home.js, src/tests/client/controller/HomeCtrl.spec.js
One the server-side, the function ```extractGithubArgs (args)```  [here](https://github.com/cla-assistant/cla-assistant/blob/master/src/server/api/webhook.js#L106) uses 'owner' while on the client side using 'user' [here](https://github.com/cla-assistant/cla-assistant/blob/master/src/client/controller/home.js#L331).
=> Cannot remove repo webhook after unlinking a repo.

README.md
Users of the CLA-Agreement tool may wonder what text to use as part of the CLA.  This pull request adds a FAQ entry pointing to http://contributoragreements.org/ for a fill-in-the-blank approach to creating the CLA text.
=> Add FAQ pointing to contributoragreements.org

src/client/controller/cla.js, src/client/controller/home.js, src/client/controller/settings.js, src/client/modals/templates/info_gist.html, src/client/modals/templates/info_share_gist.html, src/client/templates/cla.html, src/client/templates/home.html, src/client/templates/settings.html, src/server/api/cla.js, src/server/documents/cla.js, src/server/documents/org.js, src/server/documents/repo.js, src/server/services/cla.js, src/server/services/org.js, src/server/services/repo.js, src/tests/server/api/cla.js, src/tests/server/services/cla.js
One scenario I still not sure and want to discuss. When a admin want to try the new feature and re-link a repo with the same gist but mark it as a shared gist with other repos. Do we need contributors who have already signed the repo gist to sign again? 
UI:
=> Sign only once when multiple orgs or repos lined with the same gist

.travis.yml
Ref: 425478d32de6274e59fd9d1ac0b71c607af7ea40
=> Travis CI should use nodejs v8 as defined in package.json

README.md
We've had a couple of Dependabot users struggle to whitelist Dependabot in CLA Assistant.
I'd love https://github.com/cla-assistant/cla-assistant/issues/173 to be implemented, but in the meantime it would be good to have some simple advice in the readme. The instructions here are taken from https://github.com/greenkeeperio/greenkeeper/issues/236 (updated for the comments in [this PR](https://github.com/wireapp/wire-web-packages/pull/21)).
=> Add whitelisting bots section to readme

src/config.js, src/server/api/cla.js, src/server/services/cla.js, src/server/services/github.js, src/server/services/status.js, src/tests/server/api/cla.js, src/tests/server/services/cla.js, src/tests/server/services/status.js
Bugfixes:
1. New GitHub node package changes getting combined status API from 'getCombinedStatus' to 'getCombinedStatusForRef
2. When the input is undefined or null, hasNextPage() API of GitHub node package will throw an error. Then admin homepage will not show anything.
3. For those contributors don't have cached pull request, we should validate not only the repo pull request but also validate to shared gist repos/orgs accordingly.
Small features:
1. Add config settings to allow only need the submitter to sign instead of all the committers of a pull request.
2. When user change name, we should also identify their previous signature.
=> 3 bugfixes and 2 features

README.md
Using `js` instead of `json` seems to have a better code block highlight here.
=> Improve code block readability in README.md

src/server/services/cla.js, src/tests/server/services/cla.js
@MichaelTsengLZ could you review my changes, please? Are you ok with it?
problem 1: old CLA documents don't match the query with userId -> user is requested to sign the CLA again, this doesn't work either, because of index of the document, which doesn't consider the userId.
solution: extend query with search parameter, considering nonexistend userId
problem 2: method isSignificantPullRequest expects user token as mandatory attribute, in case user clicks the "recheck" link in the PR comment this method is also called, but there is no token provided
solution: use token of the linked item if there is no user token
=> Bugfix: Consider old style CLA documents without userId

package-lock.json, package.json, src/server/api/cla.js, src/server/app.js
1. Add no-sniff MIME type protection.
2. When contributor clicks link to recheck pull request, we should use the stored admin token to update status and comments.
3. When using hibernates, the container instance may be created without network initiated. Because mongoose will not reconnect if the first connection failed. The whole app is not working properly. Add retry function to reconnect MongoDB when the first connection failed.
=> Some small fixes

src/config.js, src/server/controller/default.js
It would be useful to be able to override the template used for the login page without modifying the source code of cla-assistant itself.
This pull request allows specifying the location of the template used for the login page in an environment variable so that an alternative login page can be used whilst leaving the installation of CLA assistant pristine.
Closes #363.
=> Allow specifying a custom login page template.

src/client/modals/editLinkedItem.js, src/client/modals/templates/editLinkedItem.html, src/client/modals/templates/whitelist_info.html, src/config.js, src/server/services/cla.js, src/tests/server/api/cla.js, src/tests/server/services/cla.js
_This PR adds functionality that was previously discussed with @KharitonOff._
+ Add optional feature flag: `organization_override_enabled`
+ With feature flag `true`, the PR webhook flow will now check to see whether the "Organization" user that is tied to the HEAD repo's branch is whitelisted (the whitelist being an existing functionality)
**N.B.: The `checkPullRequestSignatures` method has been updated to use Promises/(async/await).** This was necessary to avoid a rather messy change that would otherwise be required if the mix of Promise chains and callbacks were continued to be used. Without this, the code would've otherwise required some nasty nested Promise chains and/or duplicate calls to the `getPR` method. While I don't really like having to do so much refactoring to add this bit …
=> Check HEAD branch organization user

src/client/home.html, src/client/templates/my-cla.html, src/tests/client/controller/HomeCtrl.spec.js
GraphQL calls return `avatarUrl`. However to get user's data the server uses `api/github/call`, which returns `avatar_url`.
=> Rename avatarUrl to avatar_url for users call

CONTRIBUTING.md, src/client/modals/templates/info_gist.html
While some of the http:// links within the CLA Assistant source
base are served from hosts that may not support SSL, our scanners
have suggested these specific fixes to help make the web a little
more secure.
And keep our corporate management happy...
Specific links:
- To the main Gist homepage
- To the SAP PGP key
- To the Apache 2.0 License
My editor also trimed a few spaces at the end of lines. If this is an issue, let me know, and I will fix it.
=> Updating some URLs to the https:// prefix

src/client/controller/cla.js, src/client/controller/home.js, src/client/modals/editLinkedItem.js, src/client/services/linkItem.js, src/client/services/utils.js, src/client/templates/cla.html, src/server/api/cla.js, src/server/api/org.js, src/server/api/repo.js, src/server/app.js, src/server/controller/health.js, src/server/documents/utils.js, src/server/services/cla.js, src/tests/client/controller/ClaCtrl.spec.js, src/tests/client/controller/SettingsCtrl.spec.js, src/tests/server/api/cla.js, src/tests/server/api/org.js, src/tests/server/api/repo.js, src/tests/server/documents/utils.js, src/tests/server/services/cla.js, src/tests/server/services/repo.js
Bugfixes:
1. Whitelist should use exact match when there is no wildcard (*). We don't want to pass a `foo-like-user` when we white list `foo`.
2. When updating a linked repo, we should validate input. And should allow `whiteListPattern` and `privacyPolicy` as empty string.
3. Fix small issues when updating org/repo in UI.
4. Do not get pull request files to check significant changes, there is enough information in the pull request itself. In this way, we could avoid the Github abuse exception when there are thousands of commits in a pull request.
Security:
1. Setup cookie secure
New feature:
1. Add readiness route so that Kubernetes could better swap pods.
2. Show CLA updated date in the CLA signing page.
Refactor:
The refactor is mainly about placing callbacks with promises. It helps to …
=> Contribute to upstream

package.json
Heroku requires a `build` task in order to build the Javascript bundle, see https://devcenter.heroku.com/articles/node-with-grunt#specify-your-grunt-task-in-a-build-script for details.
This change adds a simple task to package.json so the app can be built.
=> Add build task so Heroku can build the Javascript bundle

src/server/services/github.js
In the upgrade from Github 13.1.1 to Octokit 16.18.1, a regression was introduced when responses are returned from the cache in https://github.com/cla-assistant/cla-assistant/commit/b61cba55429a0eaaca03b6b18f1755b09db59f42#diff-2b2595aac333a35247dfc324a84eb20b.
When saved to the cache, the original response is custom built and full response is stored under a new `data` key ([source](https://github.com/cla-assistant/cla-assistant/blob/master/src/server/services/github.js#L27)). Therefore any calls into that returned cache object ([example](https://github.com/cla-assistant/cla-assistant/blob/master/src/server/services/cla.js#L236)) don't have the same data structure as a fresh API call and therefore fail with errors like `Cannot read property 'id' of undefined`.
The original response looks …
=> Store full response in cache instead of custom built response object

src/server/services/pullRequest.js
👋 hey team, thanks for making such a useful + free GitHub plugin. There is just one tiny gripe I have, which is that the initial CLA signing request for a new contributor leads with a run-on sentence. Totally realize that I might be the only person in the world bothered by this, but bother me it does, so figured I'd throw up a PR and see what y'all think.
----
This sentence is a new contributor's first experience with CLA
assistant and was slightly ungrammatical.
=> Reword run-on sentence in CLA signing request

src/server/app.js, src/server/webhooks/ping.js, src/server/webhooks/pull_request.js, src/tests/server/webhooks/pull_request.js
It is possible that the `opened` action may not be the first webhook actually
received for a PR. If this should occur, users would see the CLA check for a PR
appear to hang until a new commit is pushed to the PR.
This change breaks the filtering and handling of a request into two
separately-exported functions, `accepts` and `handle`. Only acceptable
requests will be enqueued for debouncing. As a convenience to operators, the
no-op case will result in a 204 response code. I have confirmed that GitHub
treats a 204 as a successful response code in a private instance of CLA
checker.
Fixes #545
=> Fix race for out-of-order webhooks.

README.md, src/client/controller/home.js, src/client/modals/editLinkedItem.js, src/client/modals/templates/allowlist_info.html, src/client/modals/templates/editLinkedItem.html, src/client/services/linkItem.js, src/server/api/org.js, src/server/api/repo.js, src/server/documents/org.js, src/server/documents/repo.js, src/server/services/cla.js, src/server/services/org.js, src/server/services/repo.js, src/tests/acceptance_tests/allowlist_user_on_repo2.spec.js, src/tests/server/api/cla.js, src/tests/server/documents/org.js, src/tests/server/services/cla.js, src/tests/server/services/repo.js, src/tests/server/testData.js, src/tests/server/webhooks/pull_request.js
It is by now widely recognised (Examples: [1](https://www.cnet.com/news/master-and-slave-tech-terms-face-scrutiny-amid-anti-racism-efforts/), [2](https://www.reddit.com/r/golang/comments/gy9ylr/go_has_removed_all_uses_of_blacklistwhitelist_and/), [3](https://www.zdnet.com/article/mysql-drops-master-slave-and-blacklist-whitelist-terminology/)), that the use of the term “whitelist” is bad because of its racial overtone. So please rephrase where it is used. 
The term “allowlist” seems to be what usually supersedes the old term when used as a noun and just “allow” when used as a verb, maybe with small adjustments.
=> Remove usage of the word “whitelist”

src/client/controller/cla.js
Making the language clearer avoids the deterring effect of having the contributor believe they need to physically sign and email the CLA (as this is still a common process).
=> Use "agree to the CLA" instead of "sign the CLA"

src/server/api/cla.js, src/tests/server/api/cla.js
cla-assistant does not currently exclude [archived repositories](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/archiving-repositories) within `getReposNeedToValidate`. When this method returns archived repositories _that were archived with outstanding open PRs_ we subsequently attempt to update commit statuses but fail due to: `RequestError [HttpError]: Repository was archived so is read-only.`. Given the inability to update archived repositories, it would make sense for the application to ignore them.  Anecdotally, hitting this `RequestError` is enough to cause the entire npm process to crash.
This is my first PR to the project, so please feel free to direct me to a different way to accommodate this change, etc.
Note: 
- b4586f1 adds …
=> Filter Archived Repositories in getReposNeedToValidate()

Dockerfile
Use `--no-cache` with `apk`, so it'll still update repository indexes,
but leave no cache in the file system, so there will be no need to
manually clean up the apk cache anymore!
=> Improve Dockerfile `apk` command cache handling

Dockerfile
Reference - Best practices for writing Dockerfiles:
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#cmd
> CMD should almost always be used in the form of CMD ["executable","param1", "param2"…]
=> Use JSON notation for CMD's arguments in Dockerfile

Dockerfile
With this approach, we won't need to write the package list twice in the beginning and the end.
=> Simplify apk package clean up in Dockerfile with virtual package

README.md
The README.md file currently talks about "his or her GitHub account" when refering to the users GitHub account. I changed this from "his or her" to "their" to make the README inclusive towards non-binary people.
"they/their" is commonly used in the english language to refer to people of unknown or unspecified gender, as well as people who do not align with the gender binary, and therefore preferable over "his or her", especially since many states nowadays legally recognize the existence of more than two genders.
=> Make README more inclusive

src/client/templates/cla.html
This appears to be sentence like, and sentence-like things generally start with a capital letter:
```diff
-we are now taking you back to GitHub
+We are now taking you back to GitHub
```
=> Capitalize sentence-like message

README.md, docker-compose.yml
This PR adds a few small instructions on how to quickly setup a mongodb for development purposes with docker. 
Also it fixes/rewords a few small things in the README.
=> add instsruction on how to setup mongodb

src/server/services/cla.js, src/tests/server/services/cla.js
This PR improves the performance of getSignedCLA() massively. 
On an instance with a lot of configured repos (like cla-assistant.io) the current implementation gets a big list of repos first and then performs a second request to determine for which of these the user has a signature on file
This implementation reverses the request order and first requests all CLAs the user has signed and then performs the lookup of repos/orgs to check if that is still the up-to-date CLA. Generally this performs way better as a lot less data needs to be transferred. In my tests I saw an improvement down from a dozen seconds to less than a second. 
Follow up to #688 //cc @rael312
=> improve request performance for getSignedCLA()

README.md, package-lock.json, package.json, src/config.js, src/server/app.js, src/server/services/logger.js
This PR uses the automatic context location via `cls-rtracer` to figure out to which http request a logging statement is associated and injects this information into the log output. 
This is very helpful to associate log entries with HTTP requests and can be used in `cla-assistant.io` to link logs to traces in GCP Cloud Logging.
Adds two environment variables to determine behavior: 
- `REQUEST_TRACE_HEADER_NAME`: Use the value of an HTTP-header to set the name. E.g. the request Id set by Cloud Run (or an ingress controller). If not set or no HTTP-header is present a random uuid is used.
- `LOG_TRACE_FIELD_NAME`: The log field to use. Defaults to `req_id`.
=> add option to associate logs with request ids

README.md, src/config.js, src/server/services/logger.js
This PR adds support for a trace prefix via `LOG_TRACE_PREFIX`. 
Additionally it adds support for opentelemtry style `traceparent` headers.
=> add trace prefix and support for traceparent opentelemetry header

package-lock.json, package.json, src/server/services/github.js
This PR removes the explicit usage of the deprecated `request` and `request-promise-native` library. 
Some dependencies are still using it, but we then have no explicit dependency on these.
It also bumps `node-fetch` to `2.6.2` to be inline with the other `node-fetch` versions (indirect dependencies of octokit libraries)
=> use node-fetch; remove request(-promise-native)

src/server/api/org.js, src/server/services/github.js, src/server/services/repo.js, src/tests/server/api/org.js, src/tests/server/services/repo.js
This PR fixes the usage of node-fetch as introduced in #754. 
`callGraphql()` now return a promise of the object and not a full request object anymore.
=> fix usage of node-fetch

package-lock.json, package.json
This PR updates the google-cloud/trace-agent to the latest version 5.1.5 fixing a whole bunch of security warnings.
=> update @google-cloud/trace-agent to 5.1.5

package-lock.json, package.json
This PR updates angularjs to 1.8.2, the latest supported version (at least until end of year). 
Additionally it moves angular to devDependencies as it is only required during build.
=> update angular to 1.8.2 and move to devDeps

package-lock.json, package.json, src/server/graphQueries/github.js, src/server/passports/github.js, src/server/services/github.js
This PR replaces the usage of `node-fetch` with the native octokit calls. Doing all our API calls through octokit.
=> use native octokit calls instead of node-fetch

.github/workflows/build.yml
Use Identity federation with OIDC to authenticate against GCP removing long-lived static GCP credentials. 
Details on the configuration can be found at: 
- https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect
- https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform
=> use GitHub Actions OIDC to authenticate against GCP

src/server/src/services/github.js, src/tests/server/services/github.js
This PR uses the explicit `createOAuthAppAuth` function when working as the OAuthApp. Currently when invoking this method following error is thrown as it tries to use the `clientId` and `clientSecret`
```
Error: [@octokit/auth-token] Token passed to createTokenAuth is not a string
at Object.createTokenAuth (/Users/d064687/github/cla-assistant/node_modules/@octokit/auth-token/dist-node/index.js:39:11)
at new Octokit (/Users/d064687/github/cla-assistant/node_modules/@octokit/core/dist-node/index.js:102:32)
at new _a (/Users/d064687/github/cla-assistant/node_modules/@octokit/core/dist-node/index.js:167:30)
at new OctokitWithDefaults (/Users/d064687/github/cla-assistant/node_modules/@octokit/core/dist-node/index.js:147:9)
at new _a (/Users/d064687/github/cla-assistant/node_modules/@octokit/cor …
```
=> use createOAuthAppAuth to create authentification when acting as the OAuthApp

src/server/src/api/repo.js, src/tests/server/api/repo.js
This PR fixes a bug where the removal of webhooks caused an unhandled rejected promise, if they got already manually removed (or some other problem). Problem was that while we had a try/catch in place to handle this case, we failed to await the promise causing it be an unhandled rejected promise outside of a try/catch.
In Node16 a unhandled promise causes the node process to exit and a hard shutdown.
=> await webhook removal to gracefully handle rejected promises

src/server/src/services/status.js, src/server/src/webhooks/merge_group.js, src/server/src/webhooks/pull_request.js
This PR adds support for GitHub [new merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).
When a PR is moved to a merge queue it first needed to pass all PR checks and then needs to pass the merge queue checks again. As the CLA is only relevant on the PR level, we just green-light any merge queue check.
To have this work, we need to listen to the new webhook event `merge_group`. This is per-default not enabled and needs to manually added to the webhook under repository -> settings -> webhooks -> CLA hook -> "Merge Group".
Alternatively the GitHub App can be enabled on the repository and will listen for both PR and Merge Group events: https://github.com/apps/cla-assistant
Fixes #972
=> add support for merge_group status checks

README.md
This PR expands README to mention two MongoDB-compatible alternatives: Cosmos DB (already discussed above) and FerretDB. I'm a maintainer of the latter. FerretDB has been [fully compatible](https://blog.ferretdb.io/using-cla-assistant-with-ferretdb/) with CLA Assistant for almost a year now. Currently, [we work with SAP](https://blogs.sap.com/2022/12/13/introduction-to-sap-hana-compatibility-layer-for-mongodb-wire-protocol/) to provide a MongoDB compatibility layer for SAP HANA.
=> Mention FerretDB
