- src/client/assets/styles/_btn.scss
- src/client/assets/styles/app.scss
- src/client/controller/home.js
- src/client/controller/settings.js
- src/client/home.html
- src/client/modals/templates/upload.html
- src/client/modals/upload.js
- src/client/templates/home.html
- src/client/templates/settings.html
- src/server/api/cla.js
- src/tests/server/api/cla.js
Let the user upload a CSV file containing GitHub usernames of users who have already signed a CLA.
> Upload CSV

- DESCRIPTION.MD
some parts are still missing before this can be merged and we can request to add
> add to github integrations page

- README.md
and testing CLA at the same time
> Welcoming gender neutral contributors

- DESCRIPTION.MD
- README.md
> Refactors DESCRIPTION.md

- src/server/services/pullRequest.js
- src/tests/server/services/pullRequest.js
https://github.com/cla-assistant/cla-assistant/issues/105#issuecomment-194215536
If you haven't signed the CLA for a project, it's very likely your first
PR ever to this project. And the first thing that happens, within
seconds, is a comment by this bot with an imperative to jump through
another hoop? Oops, I think we'd like to at least show appreciation for
their effort.
> Friendlier PR comment, helps with #105

- src/client/app.js
- src/client/controller/cla.js
- src/client/templates/404.html
- src/client/templates/cla.html
- src/server/services/cla.js
- src/server/services/repo.js
- src/tests/server/services/cla.js
- src/tests/server/services/repo.js
Added error pages for non-existing repositories, repositories that do not have a CLA and for pages that do not exist(404). This solves issue #48.
The actual error pages may need some better design.
> Error pages

- src/server/services/repo.js
> Check author before committer (#2)

- README.md
> remove RN badge

- .github/stale.yml
add probot to close out inactive issues
> add probot for stale/ inactive issues

- .github/invite-contributors.yml
invite new contributors to the `contributors` team
> add commiters automatically to team

- .github/settings.yml
add integration to manage settings in a file
> change settings via probot

- .github/config.yml
request more information for empty issues/ pull requests
> probot integration to ask for more info on pr or issue

- Dockerfile
To make the Docker image smaller.
> Clean up Alpine apk cache in Dockerfile

- README.md
This could help improve the readability :)
> Add "Table of Contents" of README to improve readability

- README.md
> rename repo_public to public_repo

- src/client/templates/cla.html
Remove a comma from "I accept, that"
> Fix a typo

- .github/workflows/build.yml
Proposing removing all these empty lines from the bottom of `build.yml`.
> Remove empty lines in build.yml

- .eslintrc.js
> [WIP] Validate PR #535

- src/server/services/github.js
- src/server/services/octokit-network-interceptor.js
- src/tests/server/services/github.js
Hi @KharitonOff, @michael-spengler 😄  
- fixed build failure due to failing unit tests
- refactored and moved the octokit network interceptor method  to a separate file
> refactored and fixed failing build

- .github/workflows/build.yml
> Gardner pipeline

- Dockerfile
Originally made in #639 with a mistake and fixed/reverted by @ibakshay in 98705b636c65fb771b0d68c80a5a262d1fca3fc8, the problem should be fixed now!
> Simplify apk package clean up in Dockerfile with virtual package, again

- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/config.yml
- COMMON_ISSUES.md
This PR moves the list of common issues from issue #567 to a dedicated file inside the repository. Allowing to modify it via PRs. Additionally the issue template is adjusted and inside the issue template picker common issues are highlighed. 
You can preview this in https://github.com/Shegox/cla-assistant/issues/new/choose
fixes #567
> add COMMON_ISSUES as file

- package-lock.json
- package.json
This PR cleans up the dependencies and remove the following, which are nowhere used:
- btoa
- bunyan-sentry-stream
- raven
- socket.io
- valid-url
> remove no longer needed dependencies

- CHANGELOG.md
Prepare 2.9.2 release and add changelog
> add 2.9.2 changelog

- package-lock.json
- package.json
- src/server/api/cla.js
- src/server/api/repo.js
- src/server/middleware/utils.js
This PR updates `joi` to 17.4.2 and implements the required version update changes.
> update joi to 17.4.2

- CHANGELOG.md
> add 2.9.3 changelog

- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- DESCRIPTION.MD
- README.md
- src/client/login.html
This PR changes the references to the `master` branch into `main`
> rename referenced to default branch to main

- src/server/src/webhooks/pull_request.js
This PR fixes a problem where the 200 status is send before all webhook operations are finished.
> await all promises before sending status back
